nodeLinker: pnp

npmScopes:
  bestseller:
    npmAlwaysAuth: true
    npmAuthToken: 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
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-3.3.1.cjs
